version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/    
hooks:
  AfterInstall:
    - location: scripts/pull_and_run_docker.sh > /tmp/chk.log 2>&1
      timeout: 60
      runas: ec2-user
